################################################################################
# tool
################################################################################
[[plugins]]
repo   = 'mattn/benchvimrc-vim'
on_cmd = ['BenchVimrc']

################################################################################
# toml
################################################################################
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

# カーソル位置のコンテキストのファイルタイプを判定する
[[plugins]]
repo   = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']
on_ft = ['toml']

[[plugins]]
repo   = 'Shougo/context_filetype.vim'
on_ft = ['toml']

################################################################################
# Perl
################################################################################
[[plugins]]
repo = 'vim-perl/vim-perl'
on_ft = ['perl']

[[plugins]]
repo = 'ywatase/perldoc-vim'
on_ft = ['perl']

[[plugins]]
repo = 'ywatase/xslate-vim'
on_ft = ['perl','xslate']

[[plugins]]
repo  = 'moznion/vim-cpanfile'
on_ft = ['cpanfile']

[[plugins]]
repo    = 'moznion/syntastic-cpanfile'
on_ft   = ['cpanfile']
depends = ['syntastic']
build   = '../../../../../dein_local/syntastic-cpanfile/setup'

################################################################################
# Go
################################################################################
[[plugins]]
repo  = 'fatih/vim-go'
on_ft = ['go', 'gohtmltmpl']
build = 'cp gosnippets/snippets/go.snip ~/.vim/snippets'

################################################################################
# Ruby
################################################################################
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

################################################################################
# Javascript
################################################################################
[[plugins]]
repo = 'pangloss/vim-javascript'

################################################################################
# Markdown
################################################################################
[[plugins]]
repo  = 'hallison/vim-markdown'
on_ft = ['markdown']
build = 'cp snippets/markdown.snippets ~/.vim/snippets'

[[plugins]]
repo  = 'kannokanno/previm'
on_ft = ['markdown']

[[plugins]]
repo  = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo  = 'thinca/vim-ft-markdown_fold'
on_ft = ['markdown']

[[plugins]]
repo  = 'ywatase/mdt.vim'
on_ft = ['markdown']

[[plugins]]
repo  = 'ywatase/md2fswiki.vim'
on_ft = ['markdown']

################################################################################
# jinja2
################################################################################
[[plugins]]
repo = 'Glench/Vim-Jinja2-Syntax'
on_ft = ['jinja2']

################################################################################
# Clojure
################################################################################
[[plugins]]
repo    = 'jondistad/vimclojure'
on_ft   = ['clojure']

